POSTGRESQL_USERNAME: user
POSTGRESQL_PASSWORD: password
POSTGRESQL_HOST: 192.168.100.169
POSTGRESQL_PORT: 5434
POSTGRESQL_DATABASE: docdatabase

CONTAINER_PORT: 8081
ACTIVE_PROFILE: dev

EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: testspring365@gmail.com
EMAIL_PASSWORD: TestSpring123
VERIFY_EMAIL_HOST: http://localhost:8081